################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Core/lvgl/examples/anim \
Core/lvgl/examples/assets \
Core/lvgl/examples/event \
Core/lvgl/examples/get_started \
Core/lvgl/examples/layouts/flex \
Core/lvgl/examples/layouts/grid \
Core/lvgl/examples/libs/bmp \
Core/lvgl/examples/libs/freetype \
Core/lvgl/examples/libs/gif \
Core/lvgl/examples/libs/png \
Core/lvgl/examples/libs/qrcode \
Core/lvgl/examples/libs/sjpg \
Core/lvgl/examples/others/snapshot \
Core/lvgl/examples/porting \
Core/lvgl/examples/scroll \
Core/lvgl/examples/styles \
Core/lvgl/examples/widgets/animimg \
Core/lvgl/examples/widgets/arc \
Core/lvgl/examples/widgets/bar \
Core/lvgl/examples/widgets/btn \
Core/lvgl/examples/widgets/btnmatrix \
Core/lvgl/examples/widgets/calendar \
Core/lvgl/examples/widgets/canvas \
Core/lvgl/examples/widgets/chart \
Core/lvgl/examples/widgets/checkbox \
Core/lvgl/examples/widgets/colorwheel \
Core/lvgl/examples/widgets/dropdown \
Core/lvgl/examples/widgets/img \
Core/lvgl/examples/widgets/imgbtn \
Core/lvgl/examples/widgets/keyboard \
Core/lvgl/examples/widgets/label \
Core/lvgl/examples/widgets/led \
Core/lvgl/examples/widgets/line \
Core/lvgl/examples/widgets/list \
Core/lvgl/examples/widgets/meter \
Core/lvgl/examples/widgets/msgbox \
Core/lvgl/examples/widgets/obj \
Core/lvgl/examples/widgets/roller \
Core/lvgl/examples/widgets/slider \
Core/lvgl/examples/widgets/span \
Core/lvgl/examples/widgets/spinbox \
Core/lvgl/examples/widgets/spinner \
Core/lvgl/examples/widgets/switch \
Core/lvgl/examples/widgets/table \
Core/lvgl/examples/widgets/tabview \
Core/lvgl/examples/widgets/textarea \
Core/lvgl/examples/widgets/tileview \
Core/lvgl/examples/widgets/win \
Core/lvgl \
Core/lvgl/rt-thread \
Core/lvgl/src/core \
Core/lvgl/src/draw \
Core/lvgl/src/extra/layouts/flex \
Core/lvgl/src/extra/layouts/grid \
Core/lvgl/src/extra/libs/bmp \
Core/lvgl/src/extra/libs/freetype \
Core/lvgl/src/extra/libs/fsdrv \
Core/lvgl/src/extra/libs/gif \
Core/lvgl/src/extra/libs/png \
Core/lvgl/src/extra/libs/qrcode \
Core/lvgl/src/extra/libs/sjpg \
Core/lvgl/src/extra \
Core/lvgl/src/extra/others/snapshot \
Core/lvgl/src/extra/themes/basic \
Core/lvgl/src/extra/themes/default \
Core/lvgl/src/extra/themes/mono \
Core/lvgl/src/extra/widgets/animimg \
Core/lvgl/src/extra/widgets/calendar \
Core/lvgl/src/extra/widgets/chart \
Core/lvgl/src/extra/widgets/colorwheel \
Core/lvgl/src/extra/widgets/imgbtn \
Core/lvgl/src/extra/widgets/keyboard \
Core/lvgl/src/extra/widgets/led \
Core/lvgl/src/extra/widgets/list \
Core/lvgl/src/extra/widgets/meter \
Core/lvgl/src/extra/widgets/msgbox \
Core/lvgl/src/extra/widgets/span \
Core/lvgl/src/extra/widgets/spinbox \
Core/lvgl/src/extra/widgets/spinner \
Core/lvgl/src/extra/widgets/tabview \
Core/lvgl/src/extra/widgets/tileview \
Core/lvgl/src/extra/widgets/win \
Core/lvgl/src/font \
Core/lvgl/src/gpu \
Core/lvgl/src/gpu/sdl \
Core/lvgl/src/hal \
Core/lvgl/src/misc \
Core/lvgl/src/widgets \
Core/lvgl/tests/src \
Core/lvgl/tests/src/test_cases \
Core/lvgl/tests/src/test_fonts \
Core/lvgl/tests/unity \
Drivers/STM32F4xx_HAL_Driver/Src \

